name: logkit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  injectable: ^2.6.0
  get_it: ^9.2.1
  google_fonts: ^8.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  go_router: ^15.1.2
  flutter_svg: ^2.0.10
  shared_preferences:
  device_info_plus: ^11.2.2
  firebase_messaging: ^15.2.2
  image_picker: ^1.1.2
  mobile_scanner: ^5.1.1
  google_mlkit_text_recognition: ^0.13.0
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.0
  pdf: ^3.10.4
  path_provider: ^2.1.2
  open_file: ^3.3.2
  connectivity_plus: ^6.0.3
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  injectable_generator: ^2.10.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/appi_con.png"
  android: true
  ios: true